# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "megaraid_sas"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3c2aa854-94fa-4802-8838-00d24f5d5730";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C782-01C8";
    fsType = "vfat";
  };

  fileSystems."/tank" = {
    device = "tank";
    fsType = "zfs";
  };

  fileSystems."/tank/media" = {
    device = "tank/media";
    fsType = "zfs";
  };

  fileSystems."/tank/storage" = {
    device = "tank/storage";
    fsType = "zfs";
  };

  fileSystems."/tank/media/video" = {
    device = "tank/media/video";
    fsType = "zfs";
  };

  fileSystems."/tank/media/audio" = {
    device = "tank/media/audio";
    fsType = "zfs";
  };

  fileSystems."/tank/storage/rom_share" = {
    device = "tank/storage/rom_share";
    fsType = "zfs";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/08383a66-be88-4925-b56f-37c7b5a27f1a"; } ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
