{
 "title": "HWMON dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Voltages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_in_volts{instance=~\"$instance\"} * ignoring(label) group_left(label) node_hwmon_sensor_label",
     "legendFormat": "{{chip}}_{{label}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$instance\"} * ignoring(label) group_left(label) node_hwmon_sensor_label < 216",
     "legendFormat": "{{chip}}_{{label}}"
    }
   ]
  },
  {
   "title": "Fan RPM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{instance=~\"$instance\"} * ignoring(label) group_left(label) node_hwmon_sensor_label",
     "legendFormat": "{{chip}}_{{label}}"
    }
   ]
  },
  {
   "title": "CPU VRM Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_curr_amps{instance=~\"$instance\"} * ignoring(label) group_left(label) node_hwmon_sensor_label",
     "legendFormat": "{{chip}}_{{label}}"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chips",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "node_hwmon_chip_names{instance=~\"$instance\"}"
    }
   ]
  }
 ]
}